# Generated by Django 3.0.2 on 2020-01-30 13:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVerified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^0\\d{8,9}$')])),
                ('ban_list', models.ManyToManyField(related_name='banned', to=settings.AUTH_USER_MODEL)),
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('base_user',)},
            },
        ),
    ]
