# Generated by Django 3.0.4 on 2020-03-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuttlecock',
            name='remaining',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.Court'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='court_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='racket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.Racket'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('court', 'court_number', 'day_of_the_week', 'racket')},
        ),
    ]
