# Generated by Django 3.0.5 on 2020-04-17 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cbid',
            field=models.CharField(default='xx0000000000', max_length=12, validators=[django.core.validators.RegexValidator(code='nomatch', message='codes behind ID card must have 12 characters.', regex='^.{12}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='cid',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='nomatch', message='cid must be 13 digits number', regex='^[0-9]{13}$')]),
        ),
    ]
