# Generated by Django 3.0.5 on 2020-04-23 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200417_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='end',
            field=models.IntegerField(default='24', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='start',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
