# Generated by Django 3.0.4 on 2020-03-29 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200329_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttlecockbooking',
            name='day_of_the_week',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
    ]
