# Generated by Django 3.0.5 on 2020-04-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200423_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='end',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='court',
            old_name='start',
            new_name='open',
        ),
    ]
