# Generated by Django 3.0.2 on 2020-01-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_racket_shuttlecock'),
    ]

    operations = [
        migrations.AddField(
            model_name='racket',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racket',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shuttlecock',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shuttlecock',
            name='countPerUnit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shuttlecock',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
