# Generated by Django 3.0.2 on 2020-01-31 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_court_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
