# Generated by Django 3.0.2 on 2020-02-01 04:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20200201_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='court',
            name='review_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(max_length=200)),
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('court', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Court')),
            ],
            options={
                'unique_together': {('base_user', 'court')},
            },
        ),
    ]
