# Generated by Django 3.0.2 on 2020-02-01 04:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20200201_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='base_user',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'court')},
        ),
    ]
