# Generated by Django 3.0.2 on 2020-02-01 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200201_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='review_count',
            new_name='score_count',
        ),
        migrations.RenameField(
            model_name='court',
            old_name='review_sum',
            new_name='score_sum',
        ),
    ]
