# Generated by Django 3.0.2 on 2020-02-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200201_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='score_count',
        ),
        migrations.RemoveField(
            model_name='court',
            name='score_sum',
        ),
    ]
