# Generated by Django 3.0.2 on 2020-02-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200202_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='credit',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
