# Generated by Django 3.0.2 on 2020-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_extendeduser_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='lat',
            field=models.FloatField(default=123.123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='long',
            field=models.FloatField(default=321.31),
            preserve_default=False,
        ),
    ]
