# Generated by Django 3.0.3 on 2020-02-19 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200219_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='court_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
